# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/trynbdev',
                'doc_host': 'https://vanhp.github.io',
                'git_url': 'https://github.com/vanhp/trynbdev',
                'lib_path': 'trynbdev'},
  'syms': {'trynbdev.core': {'trynbdev.core.foo': ('core.html#foo', 'trynbdev/core.py')}}}